### PR TITLE
Install sphinx for documentation

### PR DESCRIPTION
**Pull request by guynir42**
This should allow us to automatically build documentation and have it uploaded to "readthedocs".

### CODE REVIEW

**Comment by guynir42** [comment]
Used as a reference: https://pennyhow.github.io/blog/making-readthedocs/

**Comment by guynir42** [comment]
@rknop to see the output from the doc-building go here: https://seechange--189.org.readthedocs.build/en/189/

**Review by rknop — APPROVED** [review]
I will go ahead and merge this.  I don't know a lot about Sphinx, but will learn.  In the mean time, this is a pretty minor change.

**Comment by guynir42** [comment]
Thanks!

**Pull request merged**
